const admins = ['allumsmith2023@yopmail.com'];
const userInitialPermission = {
	'/add-branches': true,
	'/add-coating': true,
	'/add-colors': true,
	'/add-cuo-order': true,
	'/add-customer': true,
	'/add-inventory': true,
	'/add-invoice': true,
	'/add-jobs': true,
	'/add-ledger': true,
	'/transport': true,
	'/add-transport': true,
	'/add-payment': true,
	'/add-product': true,
	'/add-purchase-order': true,
	'/add-storage': true,
	'/add-users-permissions': true,
	'/add-vendor': true,
	'/add-worker': true,
	'/branches': true,
	'/coating': true,
	'/colors': true,
	'/cuo-order': true,
	'/customer': true,
	'/edit-branches': true,
	'/edit-coating': true,
	'/edit-colors': true,
	'/edit-cuo-order': true,
	'/edit-customer': true,
	'/edit-invoice': true,
	'/edit-jobs': true,
	'/edit-jobs-withoutmaterial': true,
	'/edit-ledger': true,
	'/edit-product': true,
	'/edit-purchase-order': true,
	'/edit-vendor': true,
	'/edit-worker': true,
	'/finish-storage': true,
	'/inventory': true,
	'/invoice-list': true,
	'/jobs': true,
	'/ledger-list': true,
	'/product': true,
	'/purchase-order': true,
	'/raw-material': true,
	'/users': true,
	'/vendor': true,
	'/worker': true,
};

const pagesToCheck = [
	'/product',
	'/purchase-order',
	'/vendor',
	'/customer',
	'/worker',
	'/raw-material',
	'/branches',
	'/colors',
	'/coating',
	'/jobs',
	'/cuo-order',
	'/inventory',
	'/finish-storage',
	'/invoice-list',
	'/ledger-list',
	'/add-payment',
	'/transport'
];

const permissionsTypes = ['read', 'write', 'delete'];
export { admins, userInitialPermission, pagesToCheck, permissionsTypes };
