export enum PathRoutes {
	product = '/product',
	add_product = '/add-product',
	edit_product = '/edit-product',
	purchase_order = '/purchase-order',
	add_purchase_order = '/add-purchase-order',
	vendor = '/vendor',
	add_vendor = '/add-vendor',
	edit_vendor = '/edit-vendor',
	branches = '/branches',
	add_branches = '/add-branches',
	edit_branches = '/edit-branches',
	inventory = '/inventory',
	inventoryList = '/inventory-list',
	add_inventory = '/add-inventory',
	colors = '/colors',
	add_colors = '/add-colors',
	edit_colors = "/edit-colors",
	coating = '/coating',
	add_coating = '/add-coating',
	edit_coating = "/edit-coating",
	customer = '/customer',
	edit_customer = '/edit-customer',
	add_customer = '/add-customer',
	jobs = '/jobs',
	add_jobs = '/add-jobs'
}
